/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sniffer;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Level-000
 */
public class analizadorPaquete extends javax.swing.JPanel {
    
    private File fichero;
    private packet paquete;

    /**
     * Creates new form analizadorPaquete
     */
    public analizadorPaquete() {
        initComponents();
        this.TituloCabeceraIPv4.setVisible(false);
        this.TituloCabeceraTCP.setVisible(false);
        this.TituloLineaIPv4.setVisible(false);
        this.TituloLineaTCP.setVisible(false);
        this.infoCabeceraIPv4.setVisible(false);
        this.infoCabeceraTCP.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonBuscarArchivo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonGenerarAnalisis = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        etiquetanombreArchivo = new javax.swing.JLabel();
        infoTitulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        TituloLineaIPv4 = new javax.swing.JSeparator();
        TituloCabeceraIPv4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        outMacOrigen = new javax.swing.JLabel();
        infoMacOrigen = new javax.swing.JLabel();
        outMacDestino = new javax.swing.JLabel();
        infoMacDestino = new javax.swing.JLabel();
        outTipoProtocolo = new javax.swing.JLabel();
        infoTipoProtocolo = new javax.swing.JLabel();
        infoCabeceraIPv4 = new javax.swing.JPanel();
        infoVersion = new javax.swing.JLabel();
        outVersion = new javax.swing.JLabel();
        infoLongitudCabecera = new javax.swing.JLabel();
        outLongitudCabecera = new javax.swing.JLabel();
        infoLongitudCabecera1 = new javax.swing.JLabel();
        infoPrecendencia = new javax.swing.JLabel();
        infoTipoServicio = new javax.swing.JLabel();
        infoMBZ = new javax.swing.JLabel();
        outPrecendencia = new javax.swing.JLabel();
        outTipoServicio = new javax.swing.JLabel();
        outMBZ = new javax.swing.JLabel();
        infoLongitudTotalPaquete = new javax.swing.JLabel();
        infoIdentificacion = new javax.swing.JLabel();
        outLongitudTotalPaquete = new javax.swing.JLabel();
        outIdentificacion = new javax.swing.JLabel();
        infoBanderaFragmentacion = new javax.swing.JLabel();
        infoParte1 = new javax.swing.JLabel();
        infoDF = new javax.swing.JLabel();
        infoMF = new javax.swing.JLabel();
        outBF = new javax.swing.JLabel();
        outDF = new javax.swing.JLabel();
        outMF = new javax.swing.JLabel();
        infoDesplazamientoFragmentacion = new javax.swing.JLabel();
        outDesplazamientoFragmentacion = new javax.swing.JLabel();
        infoTTL = new javax.swing.JLabel();
        outTTL = new javax.swing.JLabel();
        infoProtocolo = new javax.swing.JLabel();
        outProtocolo = new javax.swing.JLabel();
        infoTTL2 = new javax.swing.JLabel();
        outChecksum = new javax.swing.JLabel();
        infoIPOrigen = new javax.swing.JLabel();
        outIPOrigen = new javax.swing.JLabel();
        outIPDestino = new javax.swing.JLabel();
        infoIPDestino = new javax.swing.JLabel();
        infoTitulo1 = new javax.swing.JLabel();
        TituloCabeceraTCP = new javax.swing.JLabel();
        TituloLineaTCP = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        outTrama = new javax.swing.JTextArea();
        jSeparator6 = new javax.swing.JSeparator();
        infoCabeceraTCP = new javax.swing.JPanel();
        infoPuertoOrigen = new javax.swing.JLabel();
        outPuertoOrigen = new javax.swing.JLabel();
        InfoPuertoDestino = new javax.swing.JLabel();
        outPuertoDestino = new javax.swing.JLabel();
        infoNumeroSecuencia = new javax.swing.JLabel();
        infoNumeroReconocimiento = new javax.swing.JLabel();
        outNumeroSecuencia = new javax.swing.JLabel();
        outNumeroReconocimiento = new javax.swing.JLabel();
        infoLongitudCabeceraTCP = new javax.swing.JLabel();
        outLongitudCabeceraTCP = new javax.swing.JLabel();
        infoReservado = new javax.swing.JLabel();
        outReservado = new javax.swing.JLabel();
        infoTituloBanderas = new javax.swing.JLabel();
        outNS = new javax.swing.JLabel();
        infoNS = new javax.swing.JLabel();
        infoCWR = new javax.swing.JLabel();
        outCWR = new javax.swing.JLabel();
        infoECE = new javax.swing.JLabel();
        outECE = new javax.swing.JLabel();
        infoURG = new javax.swing.JLabel();
        outURG = new javax.swing.JLabel();
        infoACK = new javax.swing.JLabel();
        outACK = new javax.swing.JLabel();
        infoPSH = new javax.swing.JLabel();
        outPSH = new javax.swing.JLabel();
        infoRST = new javax.swing.JLabel();
        outRST = new javax.swing.JLabel();
        infoSYN = new javax.swing.JLabel();
        outSYN = new javax.swing.JLabel();
        infoFIN = new javax.swing.JLabel();
        outFIN = new javax.swing.JLabel();
        infoTamanioVentana = new javax.swing.JLabel();
        outTamanioVentana = new javax.swing.JLabel();
        infoChecksumTCP = new javax.swing.JLabel();
        outChecksumTCP = new javax.swing.JLabel();
        infoApuntadorUrgente = new javax.swing.JLabel();
        outApuntadorUrgente = new javax.swing.JLabel();
        etiquetaPrincipal = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1000, 610));
        setPreferredSize(new java.awt.Dimension(1200, 710));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonBuscarArchivo.setBackground(new java.awt.Color(80, 175, 85));
        botonBuscarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBuscarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarArchivoMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Archivo");

        javax.swing.GroupLayout botonBuscarArchivoLayout = new javax.swing.GroupLayout(botonBuscarArchivo);
        botonBuscarArchivo.setLayout(botonBuscarArchivoLayout);
        botonBuscarArchivoLayout.setHorizontalGroup(
            botonBuscarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonBuscarArchivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        botonBuscarArchivoLayout.setVerticalGroup(
            botonBuscarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonBuscarArchivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(botonBuscarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 30));

        botonGenerarAnalisis.setBackground(new java.awt.Color(80, 175, 85));
        botonGenerarAnalisis.setForeground(new java.awt.Color(255, 255, 255));
        botonGenerarAnalisis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGenerarAnalisisMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 102, 255));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Generar Analisis");

        javax.swing.GroupLayout botonGenerarAnalisisLayout = new javax.swing.GroupLayout(botonGenerarAnalisis);
        botonGenerarAnalisis.setLayout(botonGenerarAnalisisLayout);
        botonGenerarAnalisisLayout.setHorizontalGroup(
            botonGenerarAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonGenerarAnalisisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        botonGenerarAnalisisLayout.setVerticalGroup(
            botonGenerarAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(botonGenerarAnalisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 30));

        etiquetanombreArchivo.setBackground(new java.awt.Color(255, 255, 255));
        etiquetanombreArchivo.setFont(new java.awt.Font("Roboto", 2, 10)); // NOI18N
        etiquetanombreArchivo.setForeground(new java.awt.Color(0, 0, 0));
        etiquetanombreArchivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(etiquetanombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 190, 30));

        infoTitulo.setBackground(new java.awt.Color(255, 255, 255));
        infoTitulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        infoTitulo.setForeground(new java.awt.Color(51, 51, 51));
        infoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoTitulo.setText("Seleccionar un archivo");
        infoTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(infoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, 30));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 760, 10));

        TituloLineaIPv4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(TituloLineaIPv4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 340, 10));

        TituloCabeceraIPv4.setBackground(new java.awt.Color(255, 255, 255));
        TituloCabeceraIPv4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        TituloCabeceraIPv4.setForeground(new java.awt.Color(51, 51, 51));
        TituloCabeceraIPv4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TituloCabeceraIPv4.setText("Cabecera IPv4");
        TituloCabeceraIPv4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(TituloCabeceraIPv4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 310, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        outMacOrigen.setBackground(new java.awt.Color(255, 255, 255));
        outMacOrigen.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        outMacOrigen.setForeground(new java.awt.Color(102, 102, 102));
        outMacOrigen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        infoMacOrigen.setBackground(new java.awt.Color(255, 255, 255));
        infoMacOrigen.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoMacOrigen.setForeground(new java.awt.Color(51, 51, 51));
        infoMacOrigen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoMacOrigen.setText("Dirección MAC Origen:");
        infoMacOrigen.setOpaque(true);

        outMacDestino.setBackground(new java.awt.Color(255, 255, 255));
        outMacDestino.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        outMacDestino.setForeground(new java.awt.Color(102, 102, 102));
        outMacDestino.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        infoMacDestino.setBackground(new java.awt.Color(255, 255, 255));
        infoMacDestino.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoMacDestino.setForeground(new java.awt.Color(51, 51, 51));
        infoMacDestino.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoMacDestino.setText("Dirección MAC Destino:");
        infoMacDestino.setOpaque(true);

        outTipoProtocolo.setBackground(new java.awt.Color(255, 255, 255));
        outTipoProtocolo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        outTipoProtocolo.setForeground(new java.awt.Color(51, 51, 51));
        outTipoProtocolo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        infoTipoProtocolo.setBackground(new java.awt.Color(255, 255, 255));
        infoTipoProtocolo.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoTipoProtocolo.setForeground(new java.awt.Color(51, 51, 51));
        infoTipoProtocolo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoTipoProtocolo.setText("Tipo Protocolo:");
        infoTipoProtocolo.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(infoMacOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outMacOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoMacDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(infoTipoProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(outTipoProtocolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(outMacDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(outMacOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoMacOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(outMacDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoMacDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(outTipoProtocolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoTipoProtocolo, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 350, 120));

        infoCabeceraIPv4.setBackground(new java.awt.Color(255, 255, 255));

        infoVersion.setBackground(new java.awt.Color(255, 255, 255));
        infoVersion.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoVersion.setForeground(new java.awt.Color(51, 51, 51));
        infoVersion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoVersion.setText("Version:");
        infoVersion.setOpaque(true);

        outVersion.setBackground(new java.awt.Color(255, 255, 255));
        outVersion.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outVersion.setForeground(new java.awt.Color(51, 51, 51));
        outVersion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        outVersion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        infoLongitudCabecera.setBackground(new java.awt.Color(255, 255, 255));
        infoLongitudCabecera.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoLongitudCabecera.setForeground(new java.awt.Color(51, 51, 51));
        infoLongitudCabecera.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoLongitudCabecera.setText("IHL:");
        infoLongitudCabecera.setOpaque(true);

        outLongitudCabecera.setBackground(new java.awt.Color(255, 255, 255));
        outLongitudCabecera.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outLongitudCabecera.setForeground(new java.awt.Color(51, 51, 51));

        infoLongitudCabecera1.setBackground(new java.awt.Color(255, 255, 255));
        infoLongitudCabecera1.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        infoLongitudCabecera1.setForeground(new java.awt.Color(51, 51, 51));
        infoLongitudCabecera1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoLongitudCabecera1.setText("Tipo de Servicio");
        infoLongitudCabecera1.setOpaque(true);

        infoPrecendencia.setBackground(new java.awt.Color(255, 255, 255));
        infoPrecendencia.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoPrecendencia.setForeground(new java.awt.Color(51, 51, 51));
        infoPrecendencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoPrecendencia.setText("Precedencia:");
        infoPrecendencia.setOpaque(true);

        infoTipoServicio.setBackground(new java.awt.Color(255, 255, 255));
        infoTipoServicio.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoTipoServicio.setForeground(new java.awt.Color(51, 51, 51));
        infoTipoServicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoTipoServicio.setText("Tipo de Servicio:");
        infoTipoServicio.setOpaque(true);

        infoMBZ.setBackground(new java.awt.Color(255, 255, 255));
        infoMBZ.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoMBZ.setForeground(new java.awt.Color(51, 51, 51));
        infoMBZ.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoMBZ.setText("MBZ:");
        infoMBZ.setOpaque(true);

        outPrecendencia.setBackground(new java.awt.Color(255, 255, 255));
        outPrecendencia.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outPrecendencia.setForeground(new java.awt.Color(51, 51, 51));

        outTipoServicio.setBackground(new java.awt.Color(255, 255, 255));
        outTipoServicio.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outTipoServicio.setForeground(new java.awt.Color(51, 51, 51));

        outMBZ.setBackground(new java.awt.Color(255, 255, 255));
        outMBZ.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outMBZ.setForeground(new java.awt.Color(51, 51, 51));

        infoLongitudTotalPaquete.setBackground(new java.awt.Color(255, 255, 255));
        infoLongitudTotalPaquete.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoLongitudTotalPaquete.setForeground(new java.awt.Color(51, 51, 51));
        infoLongitudTotalPaquete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoLongitudTotalPaquete.setText("Longitud Total del Paquete:");
        infoLongitudTotalPaquete.setOpaque(true);

        infoIdentificacion.setBackground(new java.awt.Color(255, 255, 255));
        infoIdentificacion.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoIdentificacion.setForeground(new java.awt.Color(51, 51, 51));
        infoIdentificacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoIdentificacion.setText("Identificacion:");
        infoIdentificacion.setOpaque(true);

        outLongitudTotalPaquete.setBackground(new java.awt.Color(255, 255, 255));
        outLongitudTotalPaquete.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outLongitudTotalPaquete.setForeground(new java.awt.Color(51, 51, 51));

        outIdentificacion.setBackground(new java.awt.Color(255, 255, 255));
        outIdentificacion.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outIdentificacion.setForeground(new java.awt.Color(51, 51, 51));

        infoBanderaFragmentacion.setBackground(new java.awt.Color(255, 255, 255));
        infoBanderaFragmentacion.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        infoBanderaFragmentacion.setForeground(new java.awt.Color(51, 51, 51));
        infoBanderaFragmentacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoBanderaFragmentacion.setText("Banderas de Fragmentacion");
        infoBanderaFragmentacion.setOpaque(true);

        infoParte1.setBackground(new java.awt.Color(255, 255, 255));
        infoParte1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoParte1.setForeground(new java.awt.Color(51, 51, 51));
        infoParte1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoParte1.setText("Parte 1:");
        infoParte1.setOpaque(true);

        infoDF.setBackground(new java.awt.Color(255, 255, 255));
        infoDF.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoDF.setForeground(new java.awt.Color(51, 51, 51));
        infoDF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoDF.setText("DF:");
        infoDF.setOpaque(true);

        infoMF.setBackground(new java.awt.Color(255, 255, 255));
        infoMF.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoMF.setForeground(new java.awt.Color(51, 51, 51));
        infoMF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoMF.setText("MF:");
        infoMF.setOpaque(true);

        outBF.setBackground(new java.awt.Color(255, 255, 255));
        outBF.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outBF.setForeground(new java.awt.Color(0, 0, 0));

        outDF.setBackground(new java.awt.Color(255, 255, 255));
        outDF.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outDF.setForeground(new java.awt.Color(51, 51, 51));

        outMF.setBackground(new java.awt.Color(255, 255, 255));
        outMF.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outMF.setForeground(new java.awt.Color(51, 51, 51));

        infoDesplazamientoFragmentacion.setBackground(new java.awt.Color(255, 255, 255));
        infoDesplazamientoFragmentacion.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoDesplazamientoFragmentacion.setForeground(new java.awt.Color(51, 51, 51));
        infoDesplazamientoFragmentacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoDesplazamientoFragmentacion.setText("Desplazamiento de la Fragmentacion:");
        infoDesplazamientoFragmentacion.setOpaque(true);

        outDesplazamientoFragmentacion.setBackground(new java.awt.Color(255, 255, 255));
        outDesplazamientoFragmentacion.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outDesplazamientoFragmentacion.setForeground(new java.awt.Color(51, 51, 51));

        infoTTL.setBackground(new java.awt.Color(255, 255, 255));
        infoTTL.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoTTL.setForeground(new java.awt.Color(51, 51, 51));
        infoTTL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoTTL.setText("Tiempo de vida (TTL)");
        infoTTL.setOpaque(true);

        outTTL.setBackground(new java.awt.Color(255, 255, 255));
        outTTL.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outTTL.setForeground(new java.awt.Color(51, 51, 51));

        infoProtocolo.setBackground(new java.awt.Color(255, 255, 255));
        infoProtocolo.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoProtocolo.setForeground(new java.awt.Color(51, 51, 51));
        infoProtocolo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoProtocolo.setText("Protocolo");
        infoProtocolo.setOpaque(true);

        outProtocolo.setBackground(new java.awt.Color(255, 255, 255));
        outProtocolo.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outProtocolo.setForeground(new java.awt.Color(51, 51, 51));

        infoTTL2.setBackground(new java.awt.Color(255, 255, 255));
        infoTTL2.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoTTL2.setForeground(new java.awt.Color(51, 51, 51));
        infoTTL2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoTTL2.setText("Checksum");
        infoTTL2.setOpaque(true);

        outChecksum.setBackground(new java.awt.Color(255, 255, 255));
        outChecksum.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outChecksum.setForeground(new java.awt.Color(51, 51, 51));

        infoIPOrigen.setBackground(new java.awt.Color(255, 255, 255));
        infoIPOrigen.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoIPOrigen.setForeground(new java.awt.Color(51, 51, 51));
        infoIPOrigen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoIPOrigen.setText("IP Origen");
        infoIPOrigen.setOpaque(true);

        outIPOrigen.setBackground(new java.awt.Color(255, 255, 255));
        outIPOrigen.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outIPOrigen.setForeground(new java.awt.Color(51, 51, 51));

        outIPDestino.setBackground(new java.awt.Color(255, 255, 255));
        outIPDestino.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outIPDestino.setForeground(new java.awt.Color(51, 51, 51));

        infoIPDestino.setBackground(new java.awt.Color(255, 255, 255));
        infoIPDestino.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoIPDestino.setForeground(new java.awt.Color(51, 51, 51));
        infoIPDestino.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoIPDestino.setText("IP Destino");
        infoIPDestino.setOpaque(true);

        javax.swing.GroupLayout infoCabeceraIPv4Layout = new javax.swing.GroupLayout(infoCabeceraIPv4);
        infoCabeceraIPv4.setLayout(infoCabeceraIPv4Layout);
        infoCabeceraIPv4Layout.setHorizontalGroup(
            infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                        .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, infoCabeceraIPv4Layout.createSequentialGroup()
                                .addComponent(infoParte1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(outBF, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(infoBanderaFragmentacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(infoLongitudCabecera1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                                        .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(infoTipoServicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(infoMBZ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50))
                                    .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                                        .addComponent(infoPrecendencia, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(outTipoServicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(outMBZ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(outPrecendencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(infoLongitudTotalPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(outLongitudTotalPaquete, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(outIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoCabeceraIPv4Layout.createSequentialGroup()
                        .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoLongitudCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outLongitudCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                        .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoDesplazamientoFragmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoTTL, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoTTL2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoIPOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoIPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoDF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoMF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outMF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(outDesplazamientoFragmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outTTL, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outChecksum, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outIPOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outIPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(outDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        infoCabeceraIPv4Layout.setVerticalGroup(
            infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outLongitudCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLongitudCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(infoLongitudCabecera1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outPrecendencia, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoPrecendencia, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoTipoServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(outTipoServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoMBZ, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(outMBZ, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                        .addComponent(outLongitudTotalPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(outIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                        .addComponent(infoLongitudTotalPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(infoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(infoBanderaFragmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outBF, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoParte1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                        .addComponent(infoDF, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(infoMF, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                        .addComponent(outDF, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(outMF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addGroup(infoCabeceraIPv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                        .addComponent(infoDesplazamientoFragmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(infoTTL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(infoProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(infoTTL2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(infoIPOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(infoIPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoCabeceraIPv4Layout.createSequentialGroup()
                        .addComponent(outDesplazamientoFragmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(outTTL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(outProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(outChecksum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(outIPOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(outIPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(infoCabeceraIPv4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 370, 430));

        infoTitulo1.setBackground(new java.awt.Color(255, 255, 255));
        infoTitulo1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        infoTitulo1.setForeground(new java.awt.Color(51, 51, 51));
        infoTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoTitulo1.setText("Cabecera Ethernet");
        infoTitulo1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(infoTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 310, 30));

        TituloCabeceraTCP.setBackground(new java.awt.Color(255, 255, 255));
        TituloCabeceraTCP.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        TituloCabeceraTCP.setForeground(new java.awt.Color(51, 51, 51));
        TituloCabeceraTCP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TituloCabeceraTCP.setText("Cabecera TCP");
        TituloCabeceraTCP.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(TituloCabeceraTCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 310, 30));

        TituloLineaTCP.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(TituloLineaTCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 360, 10));

        outTrama.setEditable(false);
        outTrama.setBackground(new java.awt.Color(255, 255, 255));
        outTrama.setColumns(16);
        outTrama.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        outTrama.setForeground(new java.awt.Color(0, 0, 0));
        outTrama.setRows(5);
        jScrollPane2.setViewportView(outTrama);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 370, 130));

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 350, 10));

        infoCabeceraTCP.setBackground(new java.awt.Color(255, 255, 255));
        infoCabeceraTCP.setOpaque(false);

        infoPuertoOrigen.setBackground(new java.awt.Color(255, 255, 255));
        infoPuertoOrigen.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoPuertoOrigen.setForeground(new java.awt.Color(51, 51, 51));
        infoPuertoOrigen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoPuertoOrigen.setText("Puerto Origen:");
        infoPuertoOrigen.setOpaque(true);

        outPuertoOrigen.setBackground(new java.awt.Color(255, 255, 255));
        outPuertoOrigen.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outPuertoOrigen.setForeground(new java.awt.Color(51, 51, 51));
        outPuertoOrigen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        outPuertoOrigen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        InfoPuertoDestino.setBackground(new java.awt.Color(255, 255, 255));
        InfoPuertoDestino.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        InfoPuertoDestino.setForeground(new java.awt.Color(51, 51, 51));
        InfoPuertoDestino.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InfoPuertoDestino.setText("Puerto Destino:");
        InfoPuertoDestino.setOpaque(true);

        outPuertoDestino.setBackground(new java.awt.Color(255, 255, 255));
        outPuertoDestino.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outPuertoDestino.setForeground(new java.awt.Color(51, 51, 51));

        infoNumeroSecuencia.setBackground(new java.awt.Color(255, 255, 255));
        infoNumeroSecuencia.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoNumeroSecuencia.setForeground(new java.awt.Color(51, 51, 51));
        infoNumeroSecuencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoNumeroSecuencia.setText("Numero de Secuencia:");
        infoNumeroSecuencia.setOpaque(true);

        infoNumeroReconocimiento.setBackground(new java.awt.Color(255, 255, 255));
        infoNumeroReconocimiento.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoNumeroReconocimiento.setForeground(new java.awt.Color(51, 51, 51));
        infoNumeroReconocimiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoNumeroReconocimiento.setText("Numero de Reconocimiento:");
        infoNumeroReconocimiento.setOpaque(true);

        outNumeroSecuencia.setBackground(new java.awt.Color(255, 255, 255));
        outNumeroSecuencia.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outNumeroSecuencia.setForeground(new java.awt.Color(51, 51, 51));

        outNumeroReconocimiento.setBackground(new java.awt.Color(255, 255, 255));
        outNumeroReconocimiento.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outNumeroReconocimiento.setForeground(new java.awt.Color(51, 51, 51));

        infoLongitudCabeceraTCP.setBackground(new java.awt.Color(255, 255, 255));
        infoLongitudCabeceraTCP.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoLongitudCabeceraTCP.setForeground(new java.awt.Color(51, 51, 51));
        infoLongitudCabeceraTCP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoLongitudCabeceraTCP.setText("Longitud de la Cabecera:");
        infoLongitudCabeceraTCP.setOpaque(true);

        outLongitudCabeceraTCP.setBackground(new java.awt.Color(255, 255, 255));
        outLongitudCabeceraTCP.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outLongitudCabeceraTCP.setForeground(new java.awt.Color(51, 51, 51));

        infoReservado.setBackground(new java.awt.Color(255, 255, 255));
        infoReservado.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoReservado.setForeground(new java.awt.Color(51, 51, 51));
        infoReservado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoReservado.setText("Reservado:");
        infoReservado.setOpaque(true);

        outReservado.setBackground(new java.awt.Color(255, 255, 255));
        outReservado.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outReservado.setForeground(new java.awt.Color(51, 51, 51));

        infoTituloBanderas.setBackground(new java.awt.Color(255, 255, 255));
        infoTituloBanderas.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        infoTituloBanderas.setForeground(new java.awt.Color(51, 51, 51));
        infoTituloBanderas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoTituloBanderas.setText("Banderas de Control");
        infoTituloBanderas.setOpaque(true);

        outNS.setBackground(new java.awt.Color(255, 255, 255));
        outNS.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outNS.setForeground(new java.awt.Color(51, 51, 51));

        infoNS.setBackground(new java.awt.Color(255, 255, 255));
        infoNS.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoNS.setForeground(new java.awt.Color(51, 51, 51));
        infoNS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoNS.setText("NS:");
        infoNS.setOpaque(true);

        infoCWR.setBackground(new java.awt.Color(255, 255, 255));
        infoCWR.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoCWR.setForeground(new java.awt.Color(51, 51, 51));
        infoCWR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoCWR.setText("CWR:");
        infoCWR.setOpaque(true);

        outCWR.setBackground(new java.awt.Color(255, 255, 255));
        outCWR.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outCWR.setForeground(new java.awt.Color(51, 51, 51));

        infoECE.setBackground(new java.awt.Color(255, 255, 255));
        infoECE.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoECE.setForeground(new java.awt.Color(51, 51, 51));
        infoECE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoECE.setText("ECE:");
        infoECE.setOpaque(true);

        outECE.setBackground(new java.awt.Color(255, 255, 255));
        outECE.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outECE.setForeground(new java.awt.Color(51, 51, 51));

        infoURG.setBackground(new java.awt.Color(255, 255, 255));
        infoURG.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoURG.setForeground(new java.awt.Color(51, 51, 51));
        infoURG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoURG.setText("URG:");
        infoURG.setOpaque(true);

        outURG.setBackground(new java.awt.Color(255, 255, 255));
        outURG.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outURG.setForeground(new java.awt.Color(51, 51, 51));

        infoACK.setBackground(new java.awt.Color(255, 255, 255));
        infoACK.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoACK.setForeground(new java.awt.Color(51, 51, 51));
        infoACK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoACK.setText("ACK:");
        infoACK.setOpaque(true);

        outACK.setBackground(new java.awt.Color(255, 255, 255));
        outACK.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outACK.setForeground(new java.awt.Color(51, 51, 51));

        infoPSH.setBackground(new java.awt.Color(255, 255, 255));
        infoPSH.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoPSH.setForeground(new java.awt.Color(51, 51, 51));
        infoPSH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoPSH.setText("PSH:");
        infoPSH.setOpaque(true);

        outPSH.setBackground(new java.awt.Color(255, 255, 255));
        outPSH.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outPSH.setForeground(new java.awt.Color(51, 51, 51));

        infoRST.setBackground(new java.awt.Color(255, 255, 255));
        infoRST.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoRST.setForeground(new java.awt.Color(51, 51, 51));
        infoRST.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoRST.setText("RST:");
        infoRST.setOpaque(true);

        outRST.setBackground(new java.awt.Color(255, 255, 255));
        outRST.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outRST.setForeground(new java.awt.Color(51, 51, 51));

        infoSYN.setBackground(new java.awt.Color(255, 255, 255));
        infoSYN.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoSYN.setForeground(new java.awt.Color(51, 51, 51));
        infoSYN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoSYN.setText("SYN:");
        infoSYN.setOpaque(true);

        outSYN.setBackground(new java.awt.Color(255, 255, 255));
        outSYN.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outSYN.setForeground(new java.awt.Color(51, 51, 51));

        infoFIN.setBackground(new java.awt.Color(255, 255, 255));
        infoFIN.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoFIN.setForeground(new java.awt.Color(51, 51, 51));
        infoFIN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoFIN.setText("FIN");
        infoFIN.setOpaque(true);

        outFIN.setBackground(new java.awt.Color(255, 255, 255));
        outFIN.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outFIN.setForeground(new java.awt.Color(51, 51, 51));

        infoTamanioVentana.setBackground(new java.awt.Color(255, 255, 255));
        infoTamanioVentana.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoTamanioVentana.setForeground(new java.awt.Color(51, 51, 51));
        infoTamanioVentana.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoTamanioVentana.setText("Tamaño de la Ventana:");
        infoTamanioVentana.setOpaque(true);

        outTamanioVentana.setBackground(new java.awt.Color(255, 255, 255));
        outTamanioVentana.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outTamanioVentana.setForeground(new java.awt.Color(51, 51, 51));

        infoChecksumTCP.setBackground(new java.awt.Color(255, 255, 255));
        infoChecksumTCP.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoChecksumTCP.setForeground(new java.awt.Color(51, 51, 51));
        infoChecksumTCP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoChecksumTCP.setText("Checksum");
        infoChecksumTCP.setOpaque(true);

        outChecksumTCP.setBackground(new java.awt.Color(255, 255, 255));
        outChecksumTCP.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outChecksumTCP.setForeground(new java.awt.Color(51, 51, 51));

        infoApuntadorUrgente.setBackground(new java.awt.Color(255, 255, 255));
        infoApuntadorUrgente.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        infoApuntadorUrgente.setForeground(new java.awt.Color(51, 51, 51));
        infoApuntadorUrgente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoApuntadorUrgente.setText("Apuntador Datos Urgentes:");
        infoApuntadorUrgente.setOpaque(true);

        outApuntadorUrgente.setBackground(new java.awt.Color(255, 255, 255));
        outApuntadorUrgente.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        outApuntadorUrgente.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout infoCabeceraTCPLayout = new javax.swing.GroupLayout(infoCabeceraTCP);
        infoCabeceraTCP.setLayout(infoCabeceraTCPLayout);
        infoCabeceraTCPLayout.setHorizontalGroup(
            infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoCabeceraTCPLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoCabeceraTCPLayout.createSequentialGroup()
                        .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(infoCabeceraTCPLayout.createSequentialGroup()
                                .addComponent(infoNS, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(outNS, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(infoTituloBanderas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoCabeceraTCPLayout.createSequentialGroup()
                                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(infoLongitudCabeceraTCP, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(infoNumeroReconocimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                                    .addComponent(infoReservado, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(outReservado, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(outNumeroReconocimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(outLongitudCabeceraTCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoCabeceraTCPLayout.createSequentialGroup()
                                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoCWR, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(infoECE, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(infoURG, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(infoACK, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(outACK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(outURG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(outECE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(outCWR, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                            .addGroup(infoCabeceraTCPLayout.createSequentialGroup()
                                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoPSH, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(infoRST, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(outRST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(outPSH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(infoCabeceraTCPLayout.createSequentialGroup()
                                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoApuntadorUrgente, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(infoChecksumTCP, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(outApuntadorUrgente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(outChecksumTCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(infoCabeceraTCPLayout.createSequentialGroup()
                                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoFIN, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(infoTamanioVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(outTamanioVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outFIN, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoCabeceraTCPLayout.createSequentialGroup()
                        .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, infoCabeceraTCPLayout.createSequentialGroup()
                                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoPuertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InfoPuertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(outPuertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outPuertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(infoCabeceraTCPLayout.createSequentialGroup()
                                .addComponent(infoSYN, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(outSYN, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, infoCabeceraTCPLayout.createSequentialGroup()
                                .addComponent(infoNumeroSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(outNumeroSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(346, 346, 346)))
                .addContainerGap())
        );
        infoCabeceraTCPLayout.setVerticalGroup(
            infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoCabeceraTCPLayout.createSequentialGroup()
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoCabeceraTCPLayout.createSequentialGroup()
                        .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outPuertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoPuertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(InfoPuertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(outPuertoDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoNumeroSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outNumeroSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoNumeroReconocimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outNumeroReconocimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoLongitudCabeceraTCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outLongitudCabeceraTCP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(infoTituloBanderas, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoReservado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outReservado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoNS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outNS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoCWR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outCWR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoECE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outECE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoURG, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outURG, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoACK, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outACK, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoPSH, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outPSH, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoRST, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outRST, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoSYN, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outSYN, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoFIN, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outFIN, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoTamanioVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outTamanioVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoChecksumTCP, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outChecksumTCP, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(infoCabeceraTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoApuntadorUrgente, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outApuntadorUrgente, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel1.add(infoCabeceraTCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 370, 430));

        etiquetaPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaPrincipal.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        etiquetaPrincipal.setForeground(new java.awt.Color(153, 153, 153));
        etiquetaPrincipal.setText("Seleccione un archivo para obtener informacion sobre el paquete");
        jPanel1.add(etiquetaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void botonGenerarAnalisisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGenerarAnalisisMouseClicked
        this.TituloCabeceraIPv4.setVisible(true);
        this.TituloCabeceraTCP.setVisible(true);
        this.TituloLineaIPv4.setVisible(true);
        this.TituloLineaTCP.setVisible(true);
        this.infoCabeceraIPv4.setVisible(true);
        this.infoCabeceraTCP.setVisible(true);
        
        this.etiquetaPrincipal.setVisible(false);
        
        paquete = new packet();

        paquete.readDataFile(fichero);

        this.outTrama.setText(paquete.toString());

        // Informacion Cabecera IP
        this.outMacOrigen.setText(paquete.getSourceMAC());
        this.outMacDestino.setText(paquete.getDestMAC());
        this.outTipoProtocolo.setText(paquete.getProtocolType());
        this.outVersion.setText(paquete.getVersion());
        this.outLongitudCabecera.setText(paquete.getLenghtHeader());
        this.outPrecendencia.setText(paquete.getPrecedencia());
        this.outTipoServicio.setText(paquete.getServiceType());
        this.outMBZ.setText(paquete.getMBZ());
        this.outLongitudTotalPaquete.setText(paquete.getLongitudTotalPaquete());
        this.outIdentificacion.setText(paquete.getIdentification());
        this.outBF.setText(paquete.getBF());
        this.outDF.setText(paquete.getDF());
        this.outMF.setText(paquete.getMB());
        this.outDesplazamientoFragmentacion.setText(paquete.getDesplazamientoFragmentacion());
        this.outTTL.setText(paquete.getTTL());
        this.outProtocolo.setText(paquete.getProtocolAltoNivel());
        this.outChecksum.setText(paquete.getChecksum());
        this.outIPOrigen.setText(paquete.getIPOrigen());
        this.outIPDestino.setText(paquete.getIPDestino());
        
        // Informacion Cabecera TCP
        this.outPuertoOrigen.setText(paquete.getSourcePort());
        this.outPuertoDestino.setText(paquete.getDestinationPort());
        this.outNumeroSecuencia.setText(paquete.getSequenceNumber());
        this.outNumeroReconocimiento.setText(paquete.getAckNumber());
        this.outLongitudCabeceraTCP.setText(paquete.getLenghtHeader());
        this.outReservado.setText(paquete.Reserved());
        this.outNS.setText(paquete.NS_flag());
        this.outCWR.setText(paquete.NS_flag());
        this.outECE.setText(paquete.ECE_flag());
        this.outURG.setText(paquete.URG_flag());
        this.outACK.setText(paquete.ACK_flag());
        this.outPSH.setText(paquete.PSH_flag());
        this.outRST.setText(paquete.RST_flag());
        this.outSYN.setText(paquete.SYN_flag());
        this.outFIN.setText(paquete.FIN_flag());
        this.outTamanioVentana.setText(paquete.getWindowSize());
        this.outChecksumTCP.setText(paquete.getChecksumTCP());
        this.outApuntadorUrgente.setText(paquete.getUrgPointer());
    }//GEN-LAST:event_botonGenerarAnalisisMouseClicked

    private void botonBuscarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarArchivoMouseClicked
        JFileChooser fc = new JFileChooser("C:\\Users\\Level-000\\Downloads");

        FileNameExtensionFilter filter = new FileNameExtensionFilter("* .TXT", "txt");

        fc.setFileFilter(filter);

        int selection = fc.showOpenDialog(this);

        if(selection == JFileChooser.APPROVE_OPTION){
            fichero = fc.getSelectedFile();

            this.etiquetanombreArchivo.setText(fichero.getName());
        }
    }//GEN-LAST:event_botonBuscarArchivoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InfoPuertoDestino;
    private javax.swing.JLabel TituloCabeceraIPv4;
    private javax.swing.JLabel TituloCabeceraTCP;
    private javax.swing.JSeparator TituloLineaIPv4;
    private javax.swing.JSeparator TituloLineaTCP;
    private javax.swing.JPanel botonBuscarArchivo;
    private javax.swing.JPanel botonGenerarAnalisis;
    private javax.swing.JLabel etiquetaPrincipal;
    private javax.swing.JLabel etiquetanombreArchivo;
    private javax.swing.JLabel infoACK;
    private javax.swing.JLabel infoApuntadorUrgente;
    private javax.swing.JLabel infoBanderaFragmentacion;
    private javax.swing.JLabel infoCWR;
    private javax.swing.JPanel infoCabeceraIPv4;
    private javax.swing.JPanel infoCabeceraTCP;
    private javax.swing.JLabel infoChecksumTCP;
    private javax.swing.JLabel infoDF;
    private javax.swing.JLabel infoDesplazamientoFragmentacion;
    private javax.swing.JLabel infoECE;
    private javax.swing.JLabel infoFIN;
    private javax.swing.JLabel infoIPDestino;
    private javax.swing.JLabel infoIPOrigen;
    private javax.swing.JLabel infoIdentificacion;
    private javax.swing.JLabel infoLongitudCabecera;
    private javax.swing.JLabel infoLongitudCabecera1;
    private javax.swing.JLabel infoLongitudCabeceraTCP;
    private javax.swing.JLabel infoLongitudTotalPaquete;
    private javax.swing.JLabel infoMBZ;
    private javax.swing.JLabel infoMF;
    private javax.swing.JLabel infoMacDestino;
    private javax.swing.JLabel infoMacOrigen;
    private javax.swing.JLabel infoNS;
    private javax.swing.JLabel infoNumeroReconocimiento;
    private javax.swing.JLabel infoNumeroSecuencia;
    private javax.swing.JLabel infoPSH;
    private javax.swing.JLabel infoParte1;
    private javax.swing.JLabel infoPrecendencia;
    private javax.swing.JLabel infoProtocolo;
    private javax.swing.JLabel infoPuertoOrigen;
    private javax.swing.JLabel infoRST;
    private javax.swing.JLabel infoReservado;
    private javax.swing.JLabel infoSYN;
    private javax.swing.JLabel infoTTL;
    private javax.swing.JLabel infoTTL2;
    private javax.swing.JLabel infoTamanioVentana;
    private javax.swing.JLabel infoTipoProtocolo;
    private javax.swing.JLabel infoTipoServicio;
    private javax.swing.JLabel infoTitulo;
    private javax.swing.JLabel infoTitulo1;
    private javax.swing.JLabel infoTituloBanderas;
    private javax.swing.JLabel infoURG;
    private javax.swing.JLabel infoVersion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel outACK;
    private javax.swing.JLabel outApuntadorUrgente;
    private javax.swing.JLabel outBF;
    private javax.swing.JLabel outCWR;
    private javax.swing.JLabel outChecksum;
    private javax.swing.JLabel outChecksumTCP;
    private javax.swing.JLabel outDF;
    private javax.swing.JLabel outDesplazamientoFragmentacion;
    private javax.swing.JLabel outECE;
    private javax.swing.JLabel outFIN;
    private javax.swing.JLabel outIPDestino;
    private javax.swing.JLabel outIPOrigen;
    private javax.swing.JLabel outIdentificacion;
    private javax.swing.JLabel outLongitudCabecera;
    private javax.swing.JLabel outLongitudCabeceraTCP;
    private javax.swing.JLabel outLongitudTotalPaquete;
    private javax.swing.JLabel outMBZ;
    private javax.swing.JLabel outMF;
    private javax.swing.JLabel outMacDestino;
    private javax.swing.JLabel outMacOrigen;
    private javax.swing.JLabel outNS;
    private javax.swing.JLabel outNumeroReconocimiento;
    private javax.swing.JLabel outNumeroSecuencia;
    private javax.swing.JLabel outPSH;
    private javax.swing.JLabel outPrecendencia;
    private javax.swing.JLabel outProtocolo;
    private javax.swing.JLabel outPuertoDestino;
    private javax.swing.JLabel outPuertoOrigen;
    private javax.swing.JLabel outRST;
    private javax.swing.JLabel outReservado;
    private javax.swing.JLabel outSYN;
    private javax.swing.JLabel outTTL;
    private javax.swing.JLabel outTamanioVentana;
    private javax.swing.JLabel outTipoProtocolo;
    private javax.swing.JLabel outTipoServicio;
    private javax.swing.JTextArea outTrama;
    private javax.swing.JLabel outURG;
    private javax.swing.JLabel outVersion;
    // End of variables declaration//GEN-END:variables
}
