/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sniffer;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Level-000
 */
public class dashboard extends javax.swing.JFrame {
    int xMouse, yMouse;
    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        paginaBienvenida p1 = new paginaBienvenida();
        
        this.infoTitulo.setText(this.infoBienvenida.getText()); 
        showPanel(p1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        db = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botonBienvenida = new javax.swing.JPanel();
        infoBienvenida = new javax.swing.JLabel();
        iconBienvenida = new javax.swing.JLabel();
        botonAnalizador = new javax.swing.JPanel();
        infoPaquete = new javax.swing.JLabel();
        iconPaquete = new javax.swing.JLabel();
        botonWifi = new javax.swing.JPanel();
        infoWifi = new javax.swing.JLabel();
        iconWifi = new javax.swing.JLabel();
        botonopc4 = new javax.swing.JPanel();
        infoOpcionInabilidato4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonopc5 = new javax.swing.JPanel();
        infoInabilidato5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        botonExit = new javax.swing.JLabel();
        title = new javax.swing.JPanel();
        infoTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setResizable(false);

        db.setBackground(new java.awt.Color(255, 255, 255));
        db.setForeground(new java.awt.Color(255, 255, 255));
        db.setPreferredSize(new java.awt.Dimension(1400, 800));
        db.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonBienvenida.setBackground(new java.awt.Color(51, 51, 51));
        botonBienvenida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBienvenida.setFocusable(false);
        botonBienvenida.setPreferredSize(new java.awt.Dimension(200, 25));
        botonBienvenida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBienvenidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonBienvenidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonBienvenidaMouseExited(evt);
            }
        });

        infoBienvenida.setBackground(new java.awt.Color(51, 102, 255));
        infoBienvenida.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        infoBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        infoBienvenida.setText("Pagina de Bienvenida");

        iconBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconBienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/icons8-casa-20.png"))); // NOI18N

        javax.swing.GroupLayout botonBienvenidaLayout = new javax.swing.GroupLayout(botonBienvenida);
        botonBienvenida.setLayout(botonBienvenidaLayout);
        botonBienvenidaLayout.setHorizontalGroup(
            botonBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonBienvenidaLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(iconBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonBienvenidaLayout.setVerticalGroup(
            botonBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconBienvenida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(infoBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(botonBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 30));

        botonAnalizador.setBackground(new java.awt.Color(51, 51, 51));
        botonAnalizador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAnalizador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAnalizadorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAnalizadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAnalizadorMouseExited(evt);
            }
        });

        infoPaquete.setBackground(new java.awt.Color(51, 102, 255));
        infoPaquete.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        infoPaquete.setForeground(new java.awt.Color(255, 255, 255));
        infoPaquete.setText("Analizar Paquete");

        iconPaquete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/icons8-paquete-20.png"))); // NOI18N

        javax.swing.GroupLayout botonAnalizadorLayout = new javax.swing.GroupLayout(botonAnalizador);
        botonAnalizador.setLayout(botonAnalizadorLayout);
        botonAnalizadorLayout.setHorizontalGroup(
            botonAnalizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonAnalizadorLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(iconPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonAnalizadorLayout.setVerticalGroup(
            botonAnalizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(iconPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(botonAnalizador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 30));

        botonWifi.setBackground(new java.awt.Color(51, 51, 51));
        botonWifi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonWifi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonWifiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonWifiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonWifiMouseExited(evt);
            }
        });

        infoWifi.setBackground(new java.awt.Color(51, 102, 255));
        infoWifi.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        infoWifi.setForeground(new java.awt.Color(255, 255, 255));
        infoWifi.setText("Wifi");

        iconWifi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconWifi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/icons8-wifi-20.png"))); // NOI18N

        javax.swing.GroupLayout botonWifiLayout = new javax.swing.GroupLayout(botonWifi);
        botonWifi.setLayout(botonWifiLayout);
        botonWifiLayout.setHorizontalGroup(
            botonWifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonWifiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconWifi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoWifi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        botonWifiLayout.setVerticalGroup(
            botonWifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoWifi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(iconWifi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(botonWifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 30));

        botonopc4.setBackground(new java.awt.Color(51, 51, 51));
        botonopc4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonopc4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonopc4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonopc4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonopc4MouseExited(evt);
            }
        });

        infoOpcionInabilidato4.setBackground(new java.awt.Color(51, 102, 255));
        infoOpcionInabilidato4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        infoOpcionInabilidato4.setForeground(new java.awt.Color(255, 255, 255));
        infoOpcionInabilidato4.setText("Opcion 4 Inabilitado");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/icons8-advertencia-20.png"))); // NOI18N

        javax.swing.GroupLayout botonopc4Layout = new javax.swing.GroupLayout(botonopc4);
        botonopc4.setLayout(botonopc4Layout);
        botonopc4Layout.setHorizontalGroup(
            botonopc4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonopc4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoOpcionInabilidato4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonopc4Layout.setVerticalGroup(
            botonopc4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(infoOpcionInabilidato4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(botonopc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, 30));

        botonopc5.setBackground(new java.awt.Color(51, 51, 51));
        botonopc5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonopc5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonopc5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonopc5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonopc5MouseExited(evt);
            }
        });

        infoInabilidato5.setBackground(new java.awt.Color(51, 102, 255));
        infoInabilidato5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        infoInabilidato5.setForeground(new java.awt.Color(255, 255, 255));
        infoInabilidato5.setText("Opcion 5 Inabilitado");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/icons8-advertencia-20.png"))); // NOI18N

        javax.swing.GroupLayout botonopc5Layout = new javax.swing.GroupLayout(botonopc5);
        botonopc5.setLayout(botonopc5Layout);
        botonopc5Layout.setHorizontalGroup(
            botonopc5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonopc5Layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoInabilidato5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonopc5Layout.setVerticalGroup(
            botonopc5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonopc5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(infoInabilidato5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(botonopc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 30));

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CB");

        jLabel11.setBackground(new java.awt.Color(51, 102, 255));
        jLabel11.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Codex");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel12.setBackground(new java.awt.Color(51, 102, 255));
        jLabel12.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Box");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 200, 70));

        jPanel4.setOpaque(false);

        jLabel13.setBackground(new java.awt.Color(51, 102, 255));
        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Herramientas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 20));

        db.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 800));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        db.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 1200, 710));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonExit.setBackground(new java.awt.Color(255, 255, 255));
        botonExit.setFont(new java.awt.Font("Roboto Light", 0, 28)); // NOI18N
        botonExit.setForeground(new java.awt.Color(0, 0, 0));
        botonExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonExit.setText("x");
        botonExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonExit.setOpaque(true);
        botonExit.setPreferredSize(new java.awt.Dimension(30, 30));
        botonExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                botonExitMouseDragged(evt);
            }
        });
        botonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonExitMousePressed(evt);
            }
        });
        header.add(botonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, -1, -1));

        db.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoTitulo.setBackground(new java.awt.Color(255, 255, 255));
        infoTitulo.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        infoTitulo.setForeground(new java.awt.Color(51, 51, 51));
        infoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        title.add(infoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, 30));

        db.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 1000, 50));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        db.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 1160, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(db, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(db, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBienvenidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBienvenidaMouseEntered
        botonBienvenida.setBackground(new Color(80, 175, 85));
    }//GEN-LAST:event_botonBienvenidaMouseEntered

    private void botonBienvenidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBienvenidaMouseExited
        botonBienvenida.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_botonBienvenidaMouseExited

    private void botonAnalizadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnalizadorMouseEntered
       this.botonAnalizador.setBackground(new Color(80, 175, 85));
    }//GEN-LAST:event_botonAnalizadorMouseEntered

    private void botonAnalizadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnalizadorMouseExited
       this.botonAnalizador.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_botonAnalizadorMouseExited

    private void botonWifiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonWifiMouseEntered
       this.botonWifi.setBackground(new Color(80, 175, 85));
    }//GEN-LAST:event_botonWifiMouseEntered

    private void botonWifiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonWifiMouseExited
       this.botonWifi.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_botonWifiMouseExited

    private void botonopc4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonopc4MouseEntered
        this.botonopc4.setBackground(new Color(80, 175, 85));
    }//GEN-LAST:event_botonopc4MouseEntered

    private void botonopc4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonopc4MouseExited
        this.botonopc4.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_botonopc4MouseExited

    private void botonopc5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonopc5MouseEntered
        this.botonopc5.setBackground(new Color(80, 175, 85));
    }//GEN-LAST:event_botonopc5MouseEntered

    private void botonopc5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonopc5MouseExited
        this.botonopc5.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_botonopc5MouseExited

    private void botonExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitMousePressed
        
    }//GEN-LAST:event_botonExitMousePressed

    private void botonExitMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitMouseDragged
        
    }//GEN-LAST:event_botonExitMouseDragged

    
    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed
  
    
    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    
    
    
    
    
    private void botonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_botonExitMouseClicked

    private void botonExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitMouseEntered
        botonExit.setBackground(Color.red);
        botonExit.setForeground(Color.white);
    }//GEN-LAST:event_botonExitMouseEntered

    private void botonExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitMouseExited
        botonExit.setBackground(Color.white);
        botonExit.setForeground(Color.black);
    }//GEN-LAST:event_botonExitMouseExited

    
    
    
    
    private void botonAnalizadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnalizadorMouseClicked
        analizadorPaquete p1 = new analizadorPaquete();
        this.infoTitulo.setText(this.infoPaquete.getText());
        showPanel(p1);
    }//GEN-LAST:event_botonAnalizadorMouseClicked

    private void botonBienvenidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBienvenidaMouseClicked
        paginaBienvenida p1 = new paginaBienvenida();
        this.infoTitulo.setText(this.infoBienvenida.getText());
        showPanel(p1);
    }//GEN-LAST:event_botonBienvenidaMouseClicked

    private void botonWifiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonWifiMouseClicked
        paginaMantenimiento p1 = new paginaMantenimiento();
        this.infoTitulo.setText(this.infoWifi.getText());
        showPanel(p1);
    }//GEN-LAST:event_botonWifiMouseClicked

    private void botonopc4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonopc4MouseClicked
        paginaMantenimiento p1 = new paginaMantenimiento();
        this.infoTitulo.setText(this.infoOpcionInabilidato4.getText());
        showPanel(p1);
    }//GEN-LAST:event_botonopc4MouseClicked

    private void botonopc5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonopc5MouseClicked
        paginaMantenimiento p1 = new paginaMantenimiento();
        this.infoTitulo.setText(this.infoInabilidato5.getText());
        showPanel(p1);
    }//GEN-LAST:event_botonopc5MouseClicked

    
    private void showPanel(JPanel p){
        p.setSize(1200, 710);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonAnalizador;
    private javax.swing.JPanel botonBienvenida;
    private javax.swing.JLabel botonExit;
    private javax.swing.JPanel botonWifi;
    private javax.swing.JPanel botonopc4;
    private javax.swing.JPanel botonopc5;
    private javax.swing.JPanel content;
    private javax.swing.JPanel db;
    private javax.swing.JPanel header;
    private javax.swing.JLabel iconBienvenida;
    private javax.swing.JLabel iconPaquete;
    private javax.swing.JLabel iconWifi;
    private javax.swing.JLabel infoBienvenida;
    private javax.swing.JLabel infoInabilidato5;
    private javax.swing.JLabel infoOpcionInabilidato4;
    private javax.swing.JLabel infoPaquete;
    private javax.swing.JLabel infoTitulo;
    private javax.swing.JLabel infoWifi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
