/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sniffer;

/**
 *
 * @author Level-000
 */
public class paginaBienvenida extends javax.swing.JPanel {

    /**
     * Creates new form paginaBienvenida
     */
    public paginaBienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaAcercaDe = new javax.swing.JPanel();
        Icono = new javax.swing.JLabel();
        Informacion = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1200, 710));

        VentanaAcercaDe.setBackground(new java.awt.Color(255, 255, 255));
        VentanaAcercaDe.setMinimumSize(new java.awt.Dimension(1000, 570));
        VentanaAcercaDe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/Blackbox-Logo2_3.png"))); // NOI18N
        VentanaAcercaDe.add(Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 230, 220));

        Informacion.setEditable(false);
        Informacion.setBackground(new java.awt.Color(255, 255, 255));
        Informacion.setColumns(20);
        Informacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Informacion.setForeground(new java.awt.Color(102, 102, 102));
        Informacion.setRows(5);
        Informacion.setText("Codex Box es un sistema desarrollado con el fin capturar y decodificar paquetes que pasan o llegan a traves de diferentes puertos.  \n\n         Desarrollado por Gustavo Hernandez Martinez bajo la supervisión del profesor Jorge Anaya Oliveros para la materia de \n                        Seminario de Solución de Problemas de Redes de  Computadoras y Protocolos de Comunicación          \n\n\t\t\t      Programado en JAVA\n\n                                                                                            Version 2.0     \n                                                                                    Derechos Reservados      \n\n                                                                     This program is licensed under the terms    \n                                                                   of the GNU General Public License version 3  ");
        Informacion.setBorder(null);
        VentanaAcercaDe.add(Informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 710, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaAcercaDe, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaAcercaDe, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icono;
    private javax.swing.JTextArea Informacion;
    private javax.swing.JPanel VentanaAcercaDe;
    // End of variables declaration//GEN-END:variables
}
